// GENERATED — NOX design tokens → Flutter ColorScheme.
// Source of truth: tokens/color.{light,dark}.tokens.json (from src/tokens.jsx).
// Seed: Color(0xFF12B4B4) (brand teal). Roles are hand-tuned — use these
// explicit schemes rather than ColorScheme.fromSeed for an exact match.
import 'package:flutter/material.dart';

const ColorScheme noxLightScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF006A6A),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFF6FF7F6),
  onPrimaryContainer: Color(0xFF002020),
  secondary: Color(0xFF4A6363),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFCCE8E7),
  onSecondaryContainer: Color(0xFF051F1F),
  tertiary: Color(0xFF6F5E00),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFFAE08A),
  onTertiaryContainer: Color(0xFF221B00),
  error: Color(0xFFBA1A1A),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFFFDAD6),
  onErrorContainer: Color(0xFF410002),
  surface: Color(0xFFF4FBFA),
  onSurface: Color(0xFF161D1D),
  onSurfaceVariant: Color(0xFF3F4948),
  outline: Color(0xFF6F7979),
  outlineVariant: Color(0xFFBEC9C8),
  inverseSurface: Color(0xFF2B3231),
  onInverseSurface: Color(0xFFECF2F1),
  inversePrimary: Color(0xFF4CDADA),
  surfaceTint: Color(0xFF006A6A),
  shadow: Color(0xFF000000),
  scrim: Color(0xFF000000),
  surfaceContainerLowest: Color(0xFFFFFFFF),
  surfaceContainerLow: Color(0xFFEFF5F4),
  surfaceContainer: Color(0xFFE9EFEE),
  surfaceContainerHigh: Color(0xFFE3EAE9),
  surfaceContainerHighest: Color(0xFFDDE4E3),
  // ignore: deprecated_member_use
  surfaceVariant: Color(0xFFDAE5E3),
);

const ColorScheme noxDarkScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFF4CDADA),
  onPrimary: Color(0xFF003737),
  primaryContainer: Color(0xFF004F4F),
  onPrimaryContainer: Color(0xFF6FF7F6),
  secondary: Color(0xFFB0CCCB),
  onSecondary: Color(0xFF1B3534),
  secondaryContainer: Color(0xFF324B4A),
  onSecondaryContainer: Color(0xFFCCE8E7),
  tertiary: Color(0xFFDEC56B),
  onTertiary: Color(0xFF3A2F00),
  tertiaryContainer: Color(0xFF534619),
  onTertiaryContainer: Color(0xFFFAE08A),
  error: Color(0xFFFFB4AB),
  onError: Color(0xFF690005),
  errorContainer: Color(0xFF93000A),
  onErrorContainer: Color(0xFFFFDAD6),
  surface: Color(0xFF0E1514),
  onSurface: Color(0xFFDDE4E3),
  onSurfaceVariant: Color(0xFFBEC9C8),
  outline: Color(0xFF899393),
  outlineVariant: Color(0xFF4E5B58),
  inverseSurface: Color(0xFFDDE4E3),
  onInverseSurface: Color(0xFF2B3231),
  inversePrimary: Color(0xFF006A6A),
  surfaceTint: Color(0xFF4CDADA),
  shadow: Color(0xFF000000),
  scrim: Color(0xFF000000),
  surfaceContainerLowest: Color(0xFF0C1312),
  surfaceContainerLow: Color(0xFF1C2423),
  surfaceContainer: Color(0xFF222A28),
  surfaceContainerHigh: Color(0xFF2C3431),
  surfaceContainerHighest: Color(0xFF37403C),
  // ignore: deprecated_member_use
  surfaceVariant: Color(0xFF3F4948),
);
